In [4]:
import scipy.linalg as lin
import numpy as np
import numpy.linalg as lin
import cmath
import math
from dyn_models.filtering_lti import gen_rand_ortho_haar_real
import pickle
from linalg_helpers import *

In [3]:
#generate a random gaussian vector
n = 5
x = np.random.randn(n)/np.sqrt(n)
print(f"x= {x}")
print(f"||x||^2= {np.linalg.norm(x)**2}")

#generate a random orthogonal matrix
#using the Haar measure
Q1 = gen_rand_ortho_haar_real(n)
Q2 = gen_rand_ortho_haar_real(n)
print(f"detQ1= {lin.det(Q1)}, detQ2= {lin.det(Q2)}")

print(f"||Q1x||^2= {np.linalg.norm(Q1@x)**2}, ||Q2x||^2= {np.linalg.norm(Q2@x)**2}")



x= [-0.37058639 -0.05326589  0.56100286  0.11749573 -0.68797822]
||x||^2= 0.9420150143771565
detQ1= 0.9999999999999997, detQ2= 1.0000000000000007
||Q1x||^2= 0.9420150143771563, ||Q2x||^2= 0.9420150143771567


In [4]:
def gen_sync_powers(sync_ind, context, Q):
    powers = np.empty((context, *Q.shape), dtype=Q.dtype)
    for i in range(context):
        p = i - sync_ind
        if p < 0:
            mat = Q.T
        else:
            mat = Q
        powers[i] = lin.matrix_power(mat, abs(p))
    return powers

def gen_sync_trace(powers, x):
    return powers @ x

In [9]:
sync_ind = 3
context = 5

x = np.random.randn(n)/np.sqrt(n)
pow1 = gen_sync_powers(sync_ind, context, Q1)
pow2 = gen_sync_powers(sync_ind, context, Q2)

x1 = gen_sync_trace(pow1, x)
x2 = gen_sync_trace(pow2, x)
print(f"x1= {x1}")
print(f"x2= {x2}")

x1= [[-0.3325998   0.1562718   0.41675527  0.27837199  0.12665283]
 [-0.47510888  0.13337606 -0.2970987  -0.25580908 -0.07097054]
 [ 0.09376479 -0.12590858 -0.23351846 -0.02776836  0.5677267 ]
 [ 0.22761422 -0.46923838  0.01608305 -0.30379759 -0.19420564]
 [ 0.52157263  0.24983321 -0.00391523  0.19659934 -0.17070174]]
x2= [[-0.36143192  0.09272912  0.05476874 -0.40579781  0.30879954]
 [ 0.26705264 -0.38380711 -0.0941311   0.38661857  0.15906217]
 [-0.48311767  0.30548741  0.10665376  0.12075279 -0.22266311]
 [ 0.22761422 -0.46923838  0.01608305 -0.30379759 -0.19420564]
 [-0.13571921  0.23735148  0.36691592  0.08188819  0.43147649]]


In [2]:
with open("/data/shared/ICL_Kalman_Experiments/train_and_test_data/ortho_haar/val_ortho_haar_ident_C_state_dim_5.pkl", "rb") as f:
    val = pickle.load(f)

In [9]:
print(type(val))
print(len(val))
print(len(val[0]["obs"]))
print(val[0]["obs"][0].shape)

<class 'list'>
100000
251
(5,)


In [15]:
print(f"val= {val[0]["obs"].shape}")

val= (251, 5)


In [3]:
with open("/data/shared/ICL_Kalman_Experiments/train_and_test_data/ortho_haar/val_ortho_sync_ident_C_state_dim_5_sync_ind_10.pkl", "rb") as f:
    val_sync = pickle.load(f)

In [15]:
print(type(val_sync))
print(len(val_sync))
print(len(val_sync[0]["obs"]))
print(val_sync[0]["obs"][0].shape)

<class 'list'>
100000
251
(5,)


In [5]:
print_matrix(val_sync[0]["obs"], "sys 0")
print_matrix(val_sync[1000]["obs"], "sys 1")

Matrix sys 0:
   -0.1675     0.2017     0.0885    -0.0526     0.3711 
    0.0706     0.2374    -0.3468     0.0468    -0.1825 
    0.2130    -0.1514    -0.0627     0.0611     0.3757 
   -0.1921     0.1549    -0.0301     0.3879    -0.0694 
    0.3918    -0.1929    -0.0089     0.0777    -0.1424 
   -0.2746    -0.2434     0.2119     0.1627     0.1053 
    0.0929     0.1297     0.1805    -0.0253    -0.3980 
   -0.0552    -0.3528     0.0203    -0.2919     0.0629 
   -0.2314     0.3207     0.2218    -0.1071    -0.0041 
    0.1232     0.0019    -0.3120    -0.2961    -0.1300 
   -0.0852     0.0980     0.0420    -0.0541     0.4422 
   -0.0113     0.2865    -0.2881     0.1558    -0.1660 
    0.3125    -0.1904    -0.0948     0.0632     0.2649 
   -0.2452     0.0626     0.0494     0.3878     0.0146 
    0.3561    -0.1095     0.0245     0.0825    -0.2663 
   -0.2177    -0.3375     0.1927     0.0537     0.1256 
   -0.0243     0.2062     0.2305    -0.0273    -0.3466 
    0.0230    -0.3038    -0.0670  